import dotenv from "dotenv";
dotenv.config();

process.env.NODE_ENV = process.env.NODE_ENV || "development";

const Config = {
  CLOUDFLARE_API_TOKEN: process.env.CLOUDFLARE_API_TOKEN!,
  CLOUDFLARE_ACCOUNT_ID: process.env.CLOUDFLARE_ACCOUNT_ID!,
  CLOUDFLARE_API_KEY: process.env.CLOUDFLARE_API_KEY!,
  CLOUDFLARE_EMAIL: process.env.CLOUDFLARE_EMAIL!,

  GITHUB_CLIENT_ID: process.env.GITHUB_CLIENT_ID!,
  GITHUB_CLIENT_SECRET: process.env.GITHUB_CLIENT_SECRET!,
  GITHUB_USER_CREDENTIAL_ID: process.env.GITHUB_USER_CREDENTIAL_ID!,
  GITHUB_USER_CREDENTIAL_TOKEN: process.env.GITHUB_USER_CREDENTIAL_TOKEN!,
  GITHUB_WEBHOOK_SECRET_KEY: process.env.GITHUB_WEBHOOK_SECRET_KEY!,
  GITHUB_WEBHOOK_PAYLOAD_URL: process.env.GITHUB_WEBHOOK_PAYLOAD_URL!,

  AWS_KEY_PAIR_NAM: process.env.AWS_KEY_PAIR_NAM!,
  AWS_SECURITY_GROUP_ID: process.env.AWS_SECURITY_GROUP_ID!,
  AWS_HOSTED_ZONE_ID: process.env.AWS_HOSTED_ZONE_ID!,
  AWS_DNS_HOSTED_ZONE_ID: process.env.AWS_DNS_HOSTED_ZONE_ID!,
  AWS_ACCESS_KEY_ID: process.env.AWS_ACCESS_KEY_ID!,
  AWS_SECRET_ACCESS_KEY: process.env.AWS_SECRET_ACCESS_KEY!,
  AWS_JAAM_SERVER_DNS_NAME: process.env.AWS_JAAM_SERVER_DNS_NAME!,
};

export default Config;
